"""Ajuste na  tabelas users - campo address_id

Revision ID: 621751887c42
Revises: 8d93b691e27b
Create Date: 2022-06-23 21:32:43.864220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '621751887c42'
down_revision = '8d93b691e27b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('address_id', sa.Integer(), nullable=True))
    op.drop_constraint('users_adress_id_fkey', 'users', type_='foreignkey')
    op.create_foreign_key(None, 'users', 'addresses', ['address_id'], ['id'])
    op.drop_column('users', 'adress_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('adress_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.create_foreign_key('users_adress_id_fkey', 'users', 'addresses', ['adress_id'], ['id'])
    op.drop_column('users', 'address_id')
    # ### end Alembic commands ###
