"""Alterando relacao 1-N users-addresses

Revision ID: 69ae673062f6
Revises: 621751887c42
Create Date: 2022-06-23 22:22:53.021655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69ae673062f6'
down_revision = '621751887c42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'addresses', 'users', ['user_id'], ['id'])
    op.drop_constraint('users_address_id_fkey', 'users', type_='foreignkey')
    op.drop_column('users', 'address_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('address_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('users_address_id_fkey', 'users', 'addresses', ['address_id'], ['id'])
    op.drop_constraint(None, 'addresses', type_='foreignkey')
    op.drop_column('addresses', 'user_id')
    # ### end Alembic commands ###
