"""Criacao - Tabela Users

Revision ID: 7830d4a9e836
Revises: 
Create Date: 2022-06-16 10:42:43.731065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "7830d4a9e836"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("email", sa.VARCHAR(length=255), nullable=False),
        sa.Column("password_hash", sa.VARCHAR(length=255), nullable=False),
        sa.Column("first_name", sa.VARCHAR(length=150), nullable=False),
        sa.Column("last_name", sa.VARCHAR(length=150), nullable=False),
        sa.Column("cpf", sa.CHAR(length=11), nullable=False),
        sa.Column("phone", sa.CHAR(length=11), nullable=True),
        sa.Column("birth_date", sa.DATE(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("cpf"),
        sa.UniqueConstraint("email"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
