"""Ajuste na realcao das tabelas users - addresses

Revision ID: 8d93b691e27b
Revises: cb607e7a9fbb
Create Date: 2022-06-23 21:30:34.348655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d93b691e27b'
down_revision = 'cb607e7a9fbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('addresses_user_fkey', 'addresses', type_='foreignkey')
    op.drop_column('addresses', 'user')
    op.add_column('users', sa.Column('adress_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'users', 'addresses', ['adress_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'adress_id')
    op.add_column('addresses', sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('addresses_user_fkey', 'addresses', 'users', ['user'], ['id'])
    # ### end Alembic commands ###
