"""Criacao da tabela addresses

Revision ID: 9ae0ac8cdc8f
Revises: 7830d4a9e836
Create Date: 2022-06-23 20:54:48.577172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9ae0ac8cdc8f"
down_revision = "7830d4a9e836"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "addresses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("street", sa.VARCHAR(length=250), nullable=False),
        sa.Column("number", sa.VARCHAR(length=100), nullable=False),
        sa.Column("complement", sa.VARCHAR(length=250), nullable=True),
        sa.Column("district", sa.VARCHAR(length=250), nullable=True),
        sa.Column("city", sa.VARCHAR(length=100), nullable=False),
        sa.Column("state", sa.CHAR(length=2), nullable=False),
        sa.Column("zip_code", sa.VARCHAR(length=8), nullable=False),
        sa.Column("main_address", sa.BOOLEAN(), nullable=True),
        sa.Column("user", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("addresses")
    # ### end Alembic commands ###
