"""Adicionado campo is_admin - tabela users

Revision ID: cb607e7a9fbb
Revises: 9ae0ac8cdc8f
Create Date: 2022-06-23 20:59:42.622430

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb607e7a9fbb'
down_revision = '9ae0ac8cdc8f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
